FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt
COPY . .

COPY ssh_server.py .

RUN mkdir -p /app/logs
RUN chmod -R 777 /app/logs

CMD ["python", "ssh_server.py"]
